### ISSUE TITLE
Installing into virtualenv which doesn't have virtualenv while it is sourced causes trace

### ISSUE THREAD

**Issue by asottile** [Yelp/pip-faster#54]
```
$ cat test.sh
rm -rf venv
virtualenv venv
. venv/bin/activate
echo mccabe > reqs.txt
curl https://raw.githubusercontent.com/Yelp/venv-update/master/venv_update.py > venv_update.py
python venv_update.py venv reqs.txt
$ bash !$
bash test.sh
New python executable in venv/bin/python
Installing setuptools, pip...done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17803  100 17803    0     0   114k      0 --:--:-- --:--:-- --:--:--  241k

Something went wrong! Sending 'venv' back in time, so make knows it's invalid.
Waiting for all subprocesses to finish...
DONE
> touch venv --reference reqs.txt --date '1 day ago'

Traceback (most recent call last):
  File "venv_update.py", line 584, in <module>
    exit(main())
  File "venv_update.py", line 566, in main
    return venv_update(stage, venv_path, reqs, venv_args)
  File "venv_update.py", line 551, in venv_update
    validate_venv(venv_path, venv_args)
  File "venv_update.py", line 353, in validate_venv
    from virtualenv import __version__ as virtualenv_version
ImportError: No module named virtualenv
```

**Comment by bukzor** [comment]
Yea it requires virtualenv.

What should I do about this use case?

**Comment by asottile** [comment]
Let's do like we do with pip and `pip install virtualenv` during stage1

**Comment by bukzor** [comment]
Makes lots of sense to me. Regression test and patch, please.

**Comment by asottile** [comment]
This is harder than it looks :/ installing virtualenv into the activated virtualenv causes it to still `ImportError` on virtualenv, putting a `try: except:` around that cause it to invalidate the virtualenv.  It then tries to use virtualenv on its own container which makes more sadness.  Here's the patch I have so far, though I'm not thinking of an easy way to accomplish this :/

```diff
diff --git a/tests/functional/simple_test.py b/tests/functional/simple_test.py
index 4c1e7e7..badc69b 100644
--- a/tests/functional/simple_test.py
+++ b/tests/functional/simple_test.py
@@ -452,3 +452,14 @@ def test_downgrade(tmpdir):
     tmpdir.chdir()
     flake8_newer()
     flake8_older()
+
+
+def test_install_in_empty_virtualenv(tmpdir):
+    tmpdir.chdir()
+    venv_update_symlink_pwd()
+    requirements('')
+    run('virtualenv', 'env')
+    run(
+        'sh', '-c',
+        '. env/bin/activate && python venv_update.py env requirements.txt',
+    )
diff --git a/venv_update.py b/venv_update.py
index a720f2b..03a94a3 100644
--- a/venv_update.py
+++ b/venv_update.py
@@ -350,7 +350,10 @@ def validate_venv(venv_path, venv_args):
     """Ensure we have a valid virtualenv."""
     import json
     from sys import executable, version
-    from virtualenv import __version__ as virtualenv_version
+    try:
+        from virtualenv import __version__ as virtualenv_version
+    except ImportError:
+        virtualenv_version = None
     # we count any existing virtualenv invalidated if any of these relevant val
     validation = (
         version,  # includes e.g. pypy version
@@ -531,6 +534,7 @@ def stage1(venv_path, reqs):
     # ensure that a compatible version of pip is installed
     run(('pip', '--version'))
     run((python, '-m', 'pip.__main__', 'install', 'pip>=1.5.0,<6.0.0'))
+    run((python, '-m', 'pip.__main__', 'install', 'virtualenv>=1.11.5,<2.0'))
 
     exec_((python, dotpy(__file__), '--stage2', venv_path) + reqs)  # never ret
 
```

**Comment by asottile** [comment]
Workaround:  `deactivate && (whatever runs venv-update) && . venv/bin/activate`

**Comment by bukzor** [comment]
I hit this just now. 

Working on it.

**Comment by mittonk** [comment]
I keep stumbling into this state as well.

**Comment by chriskuehl** [comment]
this works now!
