### ISSUE TITLE
venv_update doesn't work with Debian pip

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/pip-faster#65]
```shell
ckuehl@raptors:~$ docker run -ti debian:jessie bash
root@d728bcf544e2:/# apt-get update && \
    apt-get -y install python python-virtualenv python-pip wget
[snip]
root@d728bcf544e2:/# wget https://raw.githubusercontent.com/Yelp/pip-faster/master/venv_update.py
[snip]
root@d728bcf544e2:/# echo mock > requirements.txt
root@d728bcf544e2:/# python venv_update.py 
> usr/bin/python -m virtualenv virtualenv_run
Running virtualenv with interpreter /usr/bin/python2
New python executable in /virtualenv_run/bin/python2
Also creating executable in /virtualenv_run/bin/python
Installing setuptools, pip...done.
> pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
> virtualenv_run/bin/python -m pip.__main__ install 'pip>=1.5.0,<6.0.0'
Requirement already satisfied (use --upgrade to upgrade): pip>=1.5.0,<6.0.0 in /virtualenv_run/li
ges
Cleaning up...
> virtualenv_run/bin/python venv_update.py --stage2 virtualenv_run requirements.txt
Traceback (most recent call last):
  File "venv_update.py", line 595, in <module>
    exit(main())
  File "venv_update.py", line 577, in main
    return venv_update(stage, venv_path, reqs, venv_args)
  File "venv_update.py", line 565, in venv_update
    return stage2(venv_path, reqs)
  File "venv_update.py", line 555, in stage2
    return do_install(reqs)
  File "venv_update.py", line 408, in do_install
    previously_installed = pip_get_installed()
  File "venv_update.py", line 218, in pip_get_installed
    for dist in fresh_working_set()
  File "venv_update.py", line 280, in fresh_working_set
    from pip._vendor import pkg_resources
ImportError: No module named _vendor
```

I suspect it's because Debian devendorizes pip to comply with Policy.

This seems to fix it:
```patch
--- venv_update.py.old      2015-09-19 20:59:52.214736883 +0000
+++ venv_update.py   2015-09-19 21:00:59.326736246 +0000
@@ -277,7 +277,11 @@
 
 def fresh_working_set():
     """return a pkg_resources "working set", representing the *currently* installed pacakges"""
-    from pip._vendor import pkg_resources
+    try:
+        from pip._vendor import pkg_resources
+    except ImportError:
+        # Debian de-vendorizes vendored pip dependencies
+        import pkg_resources
 
     class WorkingSetPlusEditableInstalls(pkg_resources.WorkingSet):
 
@@ -298,7 +302,11 @@
     from collections import deque
     from pip import logger
     from pip.req import InstallRequirement
-    from pip._vendor import pkg_resources
+    try:
+        from pip._vendor import pkg_resources
+    except ImportError:
+        # Debian de-vendorizes vendored pip dependencies
+        import pkg_resources
 
     working_set = fresh_working_set()
```

**Comment by chriskuehl** [comment]
(I can submit a PR if you'd like, I didn't because I'm not sure how this project is changing in the near future.)

**Comment by asottile** [comment]
I at least think that's reasonable, :shipit:
