### ISSUE TITLE
Can't create Python 3 virtualenvs without Python 2 pip installed

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/pip-faster#66]
As far as I can tell, venv_update is able to make and manage Python 3 virtualenvs, but it fails due to running `pip --version` if Python 2's `pip` is not installed.

```shell
ckuehl@raptors:~$ docker run -ti debian:jessie bash
root@964a0ecca6d4:/# apt-get update && \
    apt-get install -y python3 python3-virtualenv python3-pip wget
[snip]

root@964a0ecca6d4:/# wget https://raw.githubusercontent.com/Yelp/pip-faster/master/venv_update.py
[snip]

# see https://github.com/Yelp/pip-faster/issues/65
root@964a0ecca6d4:/# patch -p0
--- venv_update.py.old      2015-09-19 20:59:52.214736883 +0000
+++ venv_update.py   2015-09-19 21:00:59.326736246 +0000
@@ -277,7 +277,11 @@

 def fresh_working_set():
     """return a pkg_resources "working set", representing the *currently* installed pacakges"""
-    from pip._vendor import pkg_resources
+    try:
+        from pip._vendor import pkg_resources
+    except ImportError:
+        # Debian de-vendorizes vendored pip dependencies
+        import pkg_resources

     class WorkingSetPlusEditableInstalls(pkg_resources.WorkingSet):

@@ -298,7 +302,11 @@
     from collections import deque
     from pip import logger
     from pip.req import InstallRequirement
-    from pip._vendor import pkg_resources
+    try:
+        from pip._vendor import pkg_resources
+    except ImportError:
+        # Debian de-vendorizes vendored pip dependencies
+        import pkg_resources

     working_set = fresh_working_set()
patching file venv_update.py

root@964a0ecca6d4:/# echo mock > requirements.txt

root@964a0ecca6d4:/# python3.4 venv_update.py -ppython3.4
> usr/bin/python3.4 -m virtualenv virtualenv_run -ppython3.4
Already using interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in /virtualenv_run/bin/python3.4
Also creating executable in /virtualenv_run/bin/python
Installing setuptools, pip...done.
> pip --version

Something went wrong! Sending 'virtualenv_run' back in time, so make knows it's invalid.
Waiting for all subprocesses to finish...
DONE
> touch virtualenv_run --reference requirements.txt --date '1 day ago'

Traceback (most recent call last):
  File "venv_update.py", line 603, in <module>
    exit(main())
  File "venv_update.py", line 585, in main
    return venv_update(stage, venv_path, reqs, venv_args)
  File "venv_update.py", line 571, in venv_update
    return stage1(venv_path, reqs)
  File "venv_update.py", line 551, in stage1
    run(('pip', '--version'))
  File "venv_update.py", line 97, in run
    check_call(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pip'
```

I don't know the best approach to fix it. It should be using `pip3` instead:
```shell
root@964a0ecca6d4:/# which pip
root@964a0ecca6d4:/# which pip3
/usr/bin/pip3
```

Installing `python-pip` makes venv_update succeed, but it's not actually checking the right pip version.

Another workaround is `ln -s /usr/bin/pip3 /usr/local/bin/pip` but this isn't a very good solution.

Maybe it could do something like `{sys.executable} -m pip --version` instead?

**Comment by asottile** [comment]
I think we should just change it to `python -m pip.runner` or whatever the module is.  That should fix this and be more reliable.
